### PR TITLE
Provide ability to define same vlan in different l2domains

### LINKED ISSUE #84: Add VLAN-s with same number to different l2 domains
**Is your feature request related to a problem? Please describe.**
I have created multiple l2 domains. I want to create a vlan3 in l2 domain number 1. It creates it. Now I want to create a vlan3 in l2 domain number 2. It wont create it.

**Describe the solution you'd like**
Create vlans with same number and name in different l2 domains.

**Describe alternatives you've considered**
Create the vlans using GUI.

image

image

image

**Additional context**

With the latest change from cmeissner in branch bugfix/80 that was merged to develop in codeaffen/php-ansible-modules I can not create vlans at all with the settings i wish.

```
failed: [REDACATED] (item={'vlan_id': '3', 'name': 'test1', 'description': 'test1', 'routing_domain': 'test_domain'}) => {"ansible_loop_var": "vlan", "changed": false, "msg": "Found no results while searching for vlan at /", "vlan": {"description": "test1", "name": "test1", "routing_domain": "test_domain", "vlan_id": "3"}}
failed: [REDACTED] (item={'vlan_id': '3', 'name': 'test2', 'description': 'test2', 'routing_domain': 'test_domain_2'}) => {"ansible_loop_var": "vlan", "changed": false, "msg": "Found no results while searching for vlan at /", "vlan": {"description": "test2", "name": "test2", "routing_domain": "test_domain_2", "vlan_id": "3"}}
```
```
#tasks
- name: IPAM create sections 
  codeaffen.phpipam.section:
    app_id: "ansible"
    username: "admin"
    password: "{{ docker_compose_ipam_admin_password }}"
    server_url: "https://{{ inventory_hostname }}"
    name: "{{ section.name }}"
    description: "{{ section.description }}"
    state: present
  loop: "{{ docker_compose_ipam_sections }}"
  loop_control:
    loop_var: section
  tags: admin_tasks_phpipam

- name: IPAM create L2 domains 
  codeaffen.phpipam.domain:
    app_id: "ansible"
    username: "admin"
    password: "{{ docker_compose_ipam_admin_password }}"
    server_url: "https://{{ inventory_hostname }}"
    name: "{{ l2_domain.name }}"
    description: "{{ l2_domain.description }}"
    sections: "{{ l2_domain.sections }}"
    state: present
  loop: "{{ docker_compose_ipam_l2_domains }}"
  loop_control:
    loop_var: l2_domain
  tags: admin_tasks_phpipam

- name: Create VLANS.
  codeaffen.phpipam.vlan:
    app_id: "ansible"
    username: "admin"
    password: "{{ docker_compose_ipam_admin_password }}"
    server_url: "https://{{ inventory_hostname }}"
    description: "{{ vlan.description }}"
    name: "{{ vlan.name }}"
    vlan_id: "{{ vlan.vlan_id }}"
    routing_domain: "{{ vlan.routing_domain }}"
    state: present
  loop: "{{ docker_compose_ipam_vlans }}"
  loop_control:
    loop_var: vlan
  tags: admin_tasks_phpipam

- name: Create IP subnets.
  codeaffen.phpipam.subnet:
    app_id: "ansible"
    username: "admin"
    password: "{{ docker_compose_ipam_admin_password }}"
    server_url: "https://{{ inventory_hostname }}"
    description: "{{ subnet.description }}"
    cidr: "{{ subnet.cidr }}"
    section: "{{ subnet.section }}"
    location: "{{ subnet.location|default(omit) }}"
    vlan: "{{ subnet.vlan|default(omit) }}"
      #discover_subnet: "{{ subnet.discover_subnet }}"
    dns_records: "{{ subnet.dns_records|default(omit) }}"
    nameserver: "{{ subnet.nameserver|default(omit) }}"
    state: present
  loop: "{{ docker_compose_ipam_subnets }}"
  loop_control:
    loop_var: subnet
  tags: admin_tasks_phpipam
```
```
#vars

docker_compose_ipam_sections:
  - name: "test_section"
    description: "test_section" 

docker_compose_ipam_l2_domains:
  - name: "test_domain" 
    description: "test_domain"
    sections:
      - "test_section"
  - name: "test_domain_2" 
    description: "test_domain_2"
    sections:
      - "test_section"

docker_compose_ipam_vlans:
  - vlan_id: "3"
    name: "test1"
    description: "test1"
    routing_domain: "test_domain"
  - vlan_id: "3"
    name: "test2"
    description: "test2"
    routing_domain: "test_domain_2"

docker_compose_ipam_subnets:
  - cidr: "192.168.1.0/24"
    section: "test_section"
    vlan: "3"
    description: "test"

```

### LINKED ISSUE #85: Add parameter for l2domain to `subnet` module
**Is your feature request related to a problem? Please describe.**

> Another thing to consider is that when adding a subnet to a VLAN then in the GUI it shows the different l2 domains, but when using the ansible modules, currently the l2 domain can not be specified and it will choose randomly, which l2 domain it picks.

_Originally posted by @TafkaMax in https://github.com/codeaffen/phpipam-ansible-modules/issues/84#issuecomment-1221949152_

**Describe the solution you'd like**

To solve this task it becomes necessary to add a `domain` parameter to our `subnet` module. This parameter needs to be mandatory after implementing #84. It should also defaulted to `default` as in `vlan` module.

**Describe alternatives you've considered**

For the while we don't have such a parameter we provide `default` l2domain as default for resolving vlans. In that case multi domain vlans are not supported.

**Additional context**

Simply adding the parameter with default should be enough but we need to be aware that this parameter should never presented to API as it is not supported. 

```text
$ rg api_invisible
plugins/modules/location.py
134:            resolv_location=dict(type='bool', required=False, default=False, api_invisible=True),

plugins/modules/address.py
140:            section=dict(type='str', api_invisible=True, required=True),

plugins/module_utils/phpipam_helper.py
276:            if key in self.phpipam_params and not spec.get('api_invisible', False):
305:            'api_invisible',
314:            'api_invisible',
```

### PR DESCRIPTION
**Pull request by cmeissner**
* Add option to fiter results of find_entity method
* Extend find_vlan to search l2domain it belongs to
* Add routing_domain as optional parameter
  * Default routing_domain to 'default'
* Adapt test cases and variables for current development
* Add changelog entries

Resolves #84, resolves #85

### CODE REVIEW

**Comment by cmeissner** [comment]
Can't be merged because of wrong use of `require_together` (see [failed test run](https://github.com/cmeissner/phpipam-ansible-modules/runs/8057090909?check_suite_focus=true#step:6:380)).
As `routing_domain` has a default value `vlan` is required. This does not reflect the possibility in phpipam to create subnet without define a `vlan`.
We need to use something like `required_if` here. Need to be tested further.

**Comment by cmeissner** [comment]
@TafkaMax may I ask you once again to check whether this PR implements what you requested in #84 and what I moved to #85?

**Comment by cmeissner** [comment]
> Can't be merged because of wrong use of require_together

`require_together is not required as `routing_domain` has a default value and `vlan` is not a required value on API side. If `vlan` is not set `routing_domain` is not used for any kind of operation.

**Review by gmzabos — APPROVED** [review]
LGTM

**Comment by TafkaMax** [comment]
> @TafkaMax may I ask you once again to check whether this PR implements what you requested in #84 and what I moved to #85?

Hi, I will test it now, I got back from vacation.

**Comment by TafkaMax** [comment]
Error from docs.

```
ansible-doc codeaffen.phpipam.subnet
ERROR! Unable to retrieve documentation from 'codeaffen.phpipam.subnet' due to: All (sub-)options and return values must have a 'description' field

**Comment by cmeissner** [comment]
> Error from docs.

Fixed. I think it would be great to have checks for that.

**Comment by TafkaMax** [comment]
Tested it and it works as intended.

**Pull request merged**
