### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by SummaCumWilly**
First cut of documentation updates.

### CODE REVIEW

**Comment by SummaCumWilly** [comment]
I have not tested the changes in sphinx, but I don't think there was any structural change to any of my fixes.

**Review by cmeissner — CHANGES_REQUESTED** [review]
the files located in `docs/plugins/` are created by `make doc`. Before you can run this you need to run `make doc-setup`. This will install all dependencies.
Only `docs/filters.rst` can be changed manually like you do. The markdown file to change is quite okay.

So please run `make doc` and commit the changed files. 

You can add your Name and email address to `galaxy.yml` to be sure that you will be mentioned as one of the authors. Please be sure that you use the same values you use to commit to repository. The list can be recreated from git history anytimes.

And finally please add a `changelog/fragment` to guarantee that your changes are mentioned in changelog on next release.

**Comment by cmeissner** [comment]
If you want to change the content of documentation in `docs/plugins` you have to fix the documentation comments in the module files in `plugin/modules` accordingly. Here you can put also your name and github nick as author but as you only made changes in documentation your name will be misleading for people looking for help of the original module author. So please use the `galaxy.yml` instead for that purpose.

**Comment by cmeissner** [comment]
@SummaCumWilly do you think you can provide the requested changes soon? If the PR has been merged by the end of October, it will be eligable as #hacktoberfest contribution.

**Comment by SummaCumWilly** [comment]
I battled getting the Sphinx modules added to my docker image to no avail. I don't think I'll make it, Christian.

**Comment by cmeissner** [comment]
> I battled getting the Sphinx modules added to my docker image to no avail. I don't think I'll make it, Christian.

Then it would be nice if you can apply your changes to the module files please. You can also put your data in galaxy.xml as suggested. After that I can run `make doc` to create the modified `rst` files.

**Comment by SummaCumWilly** [comment]
OK, I've updated what I think I need. I don't know if I should include the generated docs/plugins/*.rst in the PR. I'm assuming I just leave them alone. I have included a new fragment from what I think is the antsibull fragments docs specs. Let me add my changes now.

**Comment by SummaCumWilly** [comment]
OK. I see the modules you mentioned. Sorry for the confusion. Fixing now.

**Review by cmeissner — APPROVED** [review]
well done

**Comment by SummaCumWilly** [comment]
You are FAR too kind. Thanks to you for dealing with a n00b.

**Comment by cmeissner** [comment]
Your welcome! Hope to see you soon for the next contribution.

**Pull request merged**
